package com.localdirect.core

import com.localdirect.core.data.IpAddress
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test

@OptIn(ExperimentalUnsignedTypes::class)
class IpAddressTests {
    @Test
    fun basic1() {
        val ipAddress = IpAddress("192.168.0.100/24")

        assertArrayEquals(
            byteArrayOf(192.toByte(), 168.toByte(), 0, 100),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                0,
                0
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            24.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun basic2() {
        val ipAddress = IpAddress("192.168.0.1/31")

        assertArrayEquals(
            byteArrayOf(192.toByte(), 168.toByte(), 0, 1),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            31.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun basic3() {
        val ipAddress = IpAddress("192.168.100.16/8")

        assertArrayEquals(
            byteArrayOf(192.toByte(), 168.toByte(), 100, 16),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            8.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun basic4() {
        val ipAddress = IpAddress("127.0.0.1/24")

        assertArrayEquals(
            byteArrayOf(127, 0, 0, 1),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            24.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun basic5() {
        val ipAddress = IpAddress("255.255.255.255/1")

        assertArrayEquals(
            byteArrayOf(255.toByte(), 255.toByte(), 255.toByte(), 255.toByte()),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            1.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun basic6() {
        val ipAddress = IpAddress("0.0.0.0/31")

        assertArrayEquals(
            byteArrayOf(0, 0, 0, 0),
            ipAddress.octets.toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ),
            ipAddress.ipAddress.toByteArray()
        )
        assertEquals(
            31.toUByte(),
            ipAddress.mask
        )
    }

    @Test
    fun getLocalAddresses() {
        val ipAddress = IpAddress("192.168.0.100/30")
        val localAddresses = ipAddress.getLocalAddresses()

        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                0,
                0
            ),
            localAddresses[0].toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                0,
                1
            ),
            localAddresses[1].toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                1,
                0
            ),
            localAddresses[2].toByteArray()
        )
        assertArrayEquals(
            byteArrayOf(
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                1,
                1
            ),
            localAddresses[3].toByteArray()
        )
    }
}